### ISSUE TITLE
Repository gardener-integration is missing

### ISSUE THREAD

**Issue by tibeer** [osism/github-manager#36]
gardener-integration repo is missing

**Comment by tibeer** [comment]
In [this](https://github.com/osism/github-manager) repository, underneath subfolder `orgs/osism/repositories` there is a file missing (`gardener-integration.yml`) for the repository [gardener-integration](https://github.com/osism/gardener-integration)

**Comment by berendt** [comment]
@tibeer Please use more useful issue titles in the future.
