### ISSUE TITLE
Cannot add repositories

### ISSUE THREAD

**Issue by tibeer** [osism/github-manager#40]
Not sure what's causing this. Copied an existing file, renamed it and changed the key-name inside the file as well along with some parameters. Even removed the file completely and started over to make sure no typos are present. @berendt do you have an idea?

- https://github.com/osism/github-manager/actions/runs/2070713235
- https://github.com/osism/github-manager/actions/runs/2070672436
- https://github.com/osism/github-manager/actions/runs/2070610043

**Comment by berendt** [comment]
The github token had expired. I documented it in the README.
